### PR TITLE
Trial homework complete.

### PR DESCRIPTION
**Pull request by thederber**

### CODE REVIEW

**Comment by eriqande** [comment]
Hey Derek!

Gonna miss you for the next two sessions.  Please follow along on the website.  

If you could give a crack at rewriting you answers in compact, vectorized R style that would be super!  (I know, having come from C it seems so weird to not have to write for loops!).  When you are done, make another commit on the ex-test branch and then push that up to your fork. That should give me an updated pull request.  Thanks!

Have a great group piano class.

**Comment by thederber** [comment]
Alright, I sort of already did the vectorized versions, so I'll just have
to practice doing a pull request again. See you next thursday!
-Derek

On Thu, Oct 23, 2014 at 2:55 PM, Eric C. Anderson notifications@github.com
wrote:

> Hey Derek!
> 
> Gonna miss you for the next two sessions. Please follow along on the
> website.
> 
> If you could give a crack at rewriting you answers in compact, vectorized
> R style that would be super! (I know, having come from C it seems so weird
> to not have to write for loops!). When you are done, make another commit on
> the ex-test branch and then push that up to your fork. That should give me
> an updated pull request. Thanks!
> 
> Have a great group piano class.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/eriqande/rep-res-course/pull/22#issuecomment-60315704
> .

## 

-Derek Hamersly

**Comment by eriqande** [comment]
awesome!

see you next thursday!

eric

**Comment by thederber** [comment]
I don't see the "Create Pull Request" button when I push my "updated hw" commit (but I see the "updated hw" commit on this page). I followed the instructions from the "trial homework", but I am not seeing the "Create Pull Request" like last time. Do you have any ideas about what I am doing wrong?

**Comment by eriqande** [comment]
Good Job Derek.  So, it turns out that once you have opened a pull request on a branch, you don't need to open any more pull requests on it.  If you push another commit up, that automatically gets put into the original pull request.  So, what you did was just right.  I got your changes.  They are all super, though exercise #4 is not right (but few people got that, so I suspect that it was not well written/explained on my part.  The vector should include "cpetrik"      "sjohnson216"  "okisutch99"   "sczTWilliams".

**Pull request closed without merging**
