### PR TITLE
Testing the trial homework.

### PR DESCRIPTION
**Pull request by aclemento**

### CODE REVIEW

**Comment by aclemento** [comment]
I think it worked!?!

**Comment by eriqande** [comment]
Hey buddy, thanks for doing this!!  I think it just might work.

Could you try deleting all those files in the www folder and the html things, so that we have
a commit with only the Rmd file?

Thanks bro!  You're da man!

eric

**Comment by aclemento** [comment]
Working through some unison~github issues now, but I'll try to get that
done tonight.

So, do you ever sync your git_repos with unison and then access them from
different computers? Git seems to not like this behavior, and for good
reason, I think.

And that begs the question, should I not have git_repos synced by unison?
If not, should they be branches for my different computers that are placed
outside of unison-synced directories? How do you currently manage these
types of backups?

AC

**Comment by eriqande** [comment]
Hey man,
thanks.  No super big rush on it if it gets late.  I am cleaning stuff up
so that it doesn't generate all the css files and crap (and I am
gitignoring the html files!)

Are you in tomorrow?

I do unison my repositories.  Git doesn't seem to have a problem with it.
Of course, I always try to sync with unison before starting work.

eric

On Thu, Oct 16, 2014 at 10:52 PM, Anthony Clemento <notifications@github.com

**Comment by eriqande** [comment]
Anthony, I don't know if this is going to go to  you or me or where.

Playing with the reply-to links.

eric

**Comment by eriqande** [comment]
Thanks for you help on this.  I think I have things figured out.  I'm gonna close this now.

**Pull request closed without merging**
